version: 2
updates:
- package-ecosystem: bundler
  directory: "/rails"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/react-native"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/rails"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
