default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: local_track_app_development

test:
  <<: *default
  database: local_track_app_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["LOCAL_TRACK_APP_DATABASE_NAME"] %>
    host: <%= ENV["LOCAL_TRACK_APP_DATABASE_HOST"] %>
    username: <%= ENV["LOCAL_TRACK_APP_DATABASE_USERNAME"] %>
    password: <%= ENV["LOCAL_TRACK_APP_DATABASE_PASSWORD"] %>
