plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - "config/initializers/inflections.rb"

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - "db/**/*.rb"
