plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - "config/initializers/inflections.rb"

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metricis/MethodLength:
  Exclude:
    - "db/migrate/**/*.rb"

RSpec/ExampleLength:
  Enabled: false # With RSpec/MultipleExpectations already on, this does more harm than good

RSpec/MultipleExpectations:
  Enabled: true
  Max: 1

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - "db/**/*.rb"
